### ISSUE TITLE
Vite error with CJS project

### ISSUE THREAD

**Issue by leaysgur** [mayank99/ecsstatic#15]
> TypeError [ERR_INVALID_ARG_VALUE]: The argument 'filename' must be a file URL object, file URL string, or absolute path string. Received undefined

## How to reproduce

- set up demo
  - e.g. https://github.com/mayank99/ecsstatic/tree/main/demos/vite-preact
- remove `type: module` field in `package.json`
- `npm run build` or `npm run dev`
- see error above

## Work around

- Rename `vite.config.(ts|js)` to `vite.config.mjs`
- or
- Just adding `type: moudle` field in `package.json` if possible

- - - 

(Aside from that, I really favored the minimalist design. Thanks for a great library! 👏🏻  )

**Comment by mayank99** [comment]
Hey @leader22, thanks for the issue.

I fixed the error you're getting but then I ended up with another error :/
```sh
[plugin:ecsstatic] (0 , import_esbuild_plugin_noexternal.default) is not a function
/home/projects/github-a3inbg/src/Logo.tsx
    at inlineVarsUsingEsbuild (file:///home/projects/github-a3inbg/node_modules/@acab/ecsstatic/vite.cjs:245:52)
```

This is a bit puzzling. I'll investigate further when I have some more time.

sandbox 1: https://stackblitz.com/edit/github-a3inbg
sandbox 2: https://stackblitz.com/edit/github-huj6rz

**Comment by mayank99** [comment]
I've decided to remove CJS support altogether. It's not worth supporting it in 2024. Vite has also deprecated its CJS support, so everyone needs to migrate to ESM anyway.
