### ISSUE TITLE
How do we solve the problem with document, window?

### ISSUE THREAD

**Issue by usmanyunusov** [mayank99/ecsstatic#5]
```
import { css } from "@acab/ecsstatic";

const test = css`
  display: flex;
`;

const innerWidth = window.document.body.innerWidth;

export const App = () => {
  return <div class={test}>asdsad</div>;
};
```

**Comment by mayank99** [comment]
Hey @usmanyunusov, i'm not sure what you're trying to achieve and what `window` or `document` have to do with ecsstatic. Could you elaborate?

**Comment by mayank99** [comment]
Closing this for lack of info. Will reopen when if i hear back.

If i had to guess, you want to use `document.body.innerWidth` inside css. Obviously this is not possible to do at build time (there is no document when running outside browser), so you need to do it at runtime. One option is to use a CSS variable that you can pass dynamically, and use with a fallback value.

```js
const test = css`
  display: flex;
  width: var(--window-width, 100vw);
`;

const innerWidth = document?.body.innerWidth;

export const App = () => {
  return (
    <div
      class={test}
      style={{ '--window-width': innerWidth }}
    >
     ...
    </div>
  );
};
```

hope that helps
